version: "3.8"
services:
  vuejs:
    image: node:latest
    restart: always
    working_dir: /app
    volumes:
      - ./dashbordFront:/app
    ports:
      - 8080:8080
    environment:
      corsOrigin: "*"
    command: bash -c "npm install && npm run serve"

  expressjs:
    image: node:latest
    restart: always
    working_dir: /app
    volumes:
      - ./backend:/app
    environment:
      MONGODB_URI: """"""""""""""""
      PORT: 5000
      corsOrigin: "*"
    ports:
      - 5000:5000
    # depends_on:
    #   - mongo
    command: bash -c "npm install && npm start"
